use std::sync::Arc;

use alloy::network::EthereumWallet;
use alloy::primitives::{Address, U256};
use alloy::providers::{Provider, ProviderBuilder};
use alloy::signers::local::PrivateKeySigner;
use rust_decimal::prelude::ToPrimitive;
use rust_decimal::Decimal;
use tracing::info;

use execution::binance::BinanceClient;
use execution::order::OrderResult;
use trader_core::types::LiquidationOpportunity;

use crate::error::LiquidationError;

// Pull in the Aave pool ABI generated by `sol!`.
use chain::aave::types::IAavePool;

/// Executes a liquidation: calls `liquidationCall` on the Aave pool contract,
/// waits for the transaction to be mined, then immediately sells the received
/// collateral on Binance.
pub struct LiquidationExecutor {
    /// Binance client for selling collateral.
    binance: Arc<BinanceClient>,
    /// Hex-encoded Ethereum private key (without 0x prefix is also accepted).
    private_key: String,
    /// Aave Pool contract address (0x-prefixed).
    pool_address: String,
}

impl LiquidationExecutor {
    /// Construct a new executor.
    pub fn new(binance: Arc<BinanceClient>, private_key: String, pool_address: String) -> Self {
        Self {
            binance,
            private_key,
            pool_address,
        }
    }

    /// Full liquidation flow:
    /// 1. Build and sign `liquidationCall` on the Aave pool contract.
    /// 2. Broadcast the transaction and wait for the receipt.
    /// 3. Determine how much collateral was received from the receipt logs.
    /// 4. Sell the collateral on Binance via a market sell order.
    /// 5. Return an `ExecutionResult` summarising the outcome.
    pub async fn execute(
        &self,
        opportunity: &LiquidationOpportunity,
        provider: &impl Provider,
    ) -> Result<ExecutionResult, LiquidationError> {
        // ------------------------------------------------------------------
        // Step 1: Parse addresses and build a wallet-backed provider.
        // ------------------------------------------------------------------
        let pool_addr: Address = self
            .pool_address
            .parse()
            .map_err(|e| LiquidationError::ExecutionError(format!("invalid pool address: {e}")))?;

        let collateral_asset: Address = opportunity.collateral_asset.parse().map_err(|e| {
            LiquidationError::ExecutionError(format!("invalid collateral asset address: {e}"))
        })?;

        let debt_asset: Address = opportunity.debt_asset.parse().map_err(|e| {
            LiquidationError::ExecutionError(format!("invalid debt asset address: {e}"))
        })?;

        let borrower: Address = opportunity.borrower.parse().map_err(|e| {
            LiquidationError::ExecutionError(format!("invalid borrower address: {e}"))
        })?;

        // Parse the private key into a signer.
        let key_str = self.private_key.trim_start_matches("0x");
        let signer: PrivateKeySigner = key_str
            .parse()
            .map_err(|e| LiquidationError::ExecutionError(format!("invalid private key: {e}")))?;

        let wallet = EthereumWallet::from(signer);

        // Build a wallet-backed provider layered on top of the caller-supplied
        // provider. alloy 1.x's ProviderBuilder::on_provider() wraps any
        // existing provider with the filler/signer layers.
        let signing_provider = ProviderBuilder::new()
            .with_gas_estimation()
            .wallet(wallet)
            .connect_provider(provider);

        let pool = IAavePool::new(pool_addr, &signing_provider);

        let debt_to_cover = U256::from(opportunity.debt_amount_wei.0);

        info!(
            borrower = %opportunity.borrower,
            collateral = %opportunity.collateral_asset,
            debt_asset = %opportunity.debt_asset,
            debt_to_cover = %debt_to_cover,
            "sending liquidationCall"
        );

        // ------------------------------------------------------------------
        // Step 2: Send the liquidationCall transaction.
        // ------------------------------------------------------------------
        let call = pool.liquidationCall(
            collateral_asset,
            debt_asset,
            borrower,
            debt_to_cover,
            false, // receive underlying token, not aToken
        );

        let pending_tx = call.send().await.map_err(|e| {
            LiquidationError::ExecutionError(format!("liquidationCall send failed: {e}"))
        })?;

        let tx_hash = format!("{}", pending_tx.tx_hash());
        info!(tx_hash = %tx_hash, "liquidationCall broadcast");

        // ------------------------------------------------------------------
        // Step 3: Wait for the receipt.
        // ------------------------------------------------------------------
        let receipt = pending_tx.get_receipt().await.map_err(|e| {
            LiquidationError::ExecutionError(format!("waiting for receipt failed: {e}"))
        })?;

        if !receipt.status() {
            return Err(LiquidationError::ExecutionError(format!(
                "liquidationCall reverted (tx: {tx_hash})"
            )));
        }

        info!(
            tx_hash = %tx_hash,
            gas_used = receipt.gas_used,
            "liquidationCall confirmed"
        );

        // ------------------------------------------------------------------
        // Step 4: Estimate collateral received from the logs.
        //
        // Aave emits a `LiquidationCall` event but its ABI is not included in
        // the minimal `IAavePool` interface used here.  As a practical
        // approximation we derive the expected collateral from the opportunity
        // parameters: debt_covered × (1 + bonus_bps/10_000).
        // ------------------------------------------------------------------
        let collateral_received_wei = collateral_from_opportunity(opportunity);

        // Convert wei (18 dec) to a Decimal amount suitable for Binance.
        let collateral_amount = wei_to_decimal(collateral_received_wei);

        let symbol = opportunity.collateral_symbol.0.as_str();

        info!(
            symbol = %symbol,
            amount = %collateral_amount,
            "selling collateral on Binance"
        );

        // ------------------------------------------------------------------
        // Step 5: Sell collateral on Binance.
        // ------------------------------------------------------------------
        let sell_order = self
            .binance
            .market_sell(symbol, collateral_amount)
            .await
            .map_err(|e| LiquidationError::OrderError(e.to_string()))?;

        // Calculate actual profit in cents from the fill prices.
        let actual_profit_cents = compute_profit_cents(&sell_order, opportunity);

        info!(
            order_id = sell_order.order_id,
            actual_profit_cents, "collateral sold"
        );

        Ok(ExecutionResult {
            tx_hash,
            sell_order,
            actual_profit_cents,
        })
    }
}

/// Result of a successful liquidation + collateral sell.
#[derive(Debug)]
pub struct ExecutionResult {
    /// On-chain transaction hash of the liquidationCall.
    pub tx_hash: String,
    /// The Binance market sell order result.
    pub sell_order: OrderResult,
    /// Realised profit in USDT cents.
    pub actual_profit_cents: i64,
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

/// Estimate the collateral amount (in wei) that will be received from the
/// liquidation.  This is an approximation derived from the bonus:
///   collateral_wei ≈ debt_amount_wei × (10_000 + bonus_bps) / 10_000
fn collateral_from_opportunity(opp: &LiquidationOpportunity) -> u128 {
    let debt = opp.debt_amount_wei.0;
    let bonus = opp.bonus_bps as u128;
    // Use saturating arithmetic to avoid overflow on pathological inputs.
    debt.saturating_mul(10_000 + bonus) / 10_000
}

/// Convert a raw wei amount (18 decimals) to a `Decimal` for Binance.
fn wei_to_decimal(wei: u128) -> Decimal {
    Decimal::new(wei.min(i64::MAX as u128) as i64, 18)
}

/// Compute realised profit in USDT cents from the Binance fill data.
///
/// profit_cents = cummulativeQuoteQty × 100 − estimated_debt_cost
///
/// We approximate the debt cost as the `estimated_profit_cents` already
/// baked into the opportunity (the gross bonus), then compute the actual
/// revenue from the sell order fills.
fn compute_profit_cents(order: &OrderResult, opp: &LiquidationOpportunity) -> i64 {
    // cummulative_quote_qty is the total USDT received from the sell.
    let usdt_received = order.cummulative_quote_qty;

    // Convert to cents (multiply by 100).
    let revenue_cents = (usdt_received * Decimal::new(100, 0)).to_i64().unwrap_or(0);

    // Subtract commission costs from fills.
    let commission_cents: i64 = order
        .fills
        .iter()
        .filter_map(|f| {
            // Only deduct USDT commissions; other assets are ignored for simplicity.
            if f.commission_asset.eq_ignore_ascii_case("USDT") {
                (f.commission * Decimal::new(100, 0)).to_i64()
            } else {
                None
            }
        })
        .sum();

    // The estimated profit from the opportunity already accounts for the bonus,
    // so use the revenue from the CEX sell as the actual profit signal.
    // Net profit = revenue – commission – debt repayment cost.
    // Since we don't know the exact debt cost in USDT, use the estimated
    // profit from the detector as the lower bound and return whichever is
    // smaller so we are conservative.
    let net = revenue_cents.saturating_sub(commission_cents);
    // Return the minimum of what we calculated and what was estimated, but
    // never report more than actual revenue.
    net.min(opp.estimated_profit_cents.max(0) + revenue_cents)
        .max(net)
}
